### ISSUE TITLE
Invalid Handle problem

### ISSUE THREAD

**Issue by lonnietc** [melbahja/goph#45]
Hello,

I just tried to use goph to test it one of my servers that has ssh, but get an error:

```
test> go run .\examples\goph\main.go --ip 192.168.0.35 --pass --cmd ls
go: downloading github.com/pkg/sftp v1.13.4
go: downloading golang.org/x/term v0.0.0-20210927222741-03fcf44c2211
go: downloading golang.org/x/sys v0.0.0-20211031064116-611d5d643895
Enter SSH Password: panic: The handle is invalid.

goroutine 1 [running]:
main.askPass({0x5ebee3, 0xd})
        D:/dMUSE/SCP/test07/test/examples/goph/main.go:169 +0xe5 main.main()
        D:/dMUSE/SCP/test07/test/examples/goph/main.go:116 +0x13e exit status 2
```

Any thoughts on how to fix this?
Thanks

**Comment by melbahja** [comment]
Hey @lonnietc, this isn't a goph issue, it's the example CLI using `terminal.ReadPassword` which doesn't work on Windows. 

goph itself is pure Go and works fine on Windows.

A few ways around it in v2, you can use `WithKeyboardInteractive` or read password without terminal pkg.


The `main.go` example is just a demo; the library API works regardless. Going to close! 🙏
